# Generated by Django 4.2.7 on 2024-01-09 12:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address_api', '0003_alter_address_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(default=datetime.date.today)),
                ('fk_Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='address_api.address')),
            ],
            options={
                'permissions': (('can_view_all_residences', 'Can view ALL residences'), ('can_create_all_residences', 'Can create ALL residences'), ('can_update_all_residences', 'Can update ALL residences'), ('can_delete_all_residences', 'Can delete ALL residences')),
            },
        ),
        migrations.CreateModel(
            name='HOAUser_Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('fk_HOAUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('fk_Residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='hoa_api.residence')),
            ],
            options={
                'permissions': (('can_view_all_hoauser_residences', 'Can view ALL hoauser_residences'), ('can_create_all_hoauser_residences', 'Can create ALL hoauser_residences'), ('can_update_all_hoauser_residences', 'Can update ALL hoauser_residences'), ('can_delete_all_hoauser_residences', 'Can delete ALL hoauser_residences')),
            },
        ),
        migrations.AddConstraint(
            model_name='residence',
            constraint=models.UniqueConstraint(fields=('fk_Address',), name='hoa_api_residence_unique'),
        ),
        migrations.AddConstraint(
            model_name='hoauser_residence',
            constraint=models.UniqueConstraint(fields=('fk_HOAUser', 'fk_Residence'), name='hoa_api_hoauser_residence_unique'),
        ),
    ]
