# Generated by Django 4.2.7 on 2024-01-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoa_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residence',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
