# Generated by Django 4.2.7 on 2023-11-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('street_2', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('addr_state', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image')),
            ],
        ),
    ]
