# Generated by Django 4.2.7 on 2023-12-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_api', '0002_alter_address_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'permissions': (('can_view_all_addresses', 'Can view ALL addresses'), ('can_create_all_addresses', 'Can create ALL addresses'), ('can_update_all_addresses', 'Can update ALL addresses'), ('can_delete_all_addresses', 'Can delete ALL addresses'))},
        ),
    ]
