# Generated by Django 4.2.7 on 2024-01-13 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='effective_datetime',
        ),
        migrations.AddField(
            model_name='policy',
            name='effective_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
