# Generated by Django 4.2.7 on 2023-11-16 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoauser',
            name='date_joined',
        ),
    ]
