# Generated by Django 4.2.7 on 2023-11-17 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_hoauser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoauser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
