# Generated by Django 4.2.7 on 2023-11-17 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address_api', '0001_initial'),
        ('users', '0003_hoauser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoauser',
            name='fk_mailing_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='HOAUsers', to='address_api.address'),
        ),
    ]
