# Generated by Django 4.2.7 on 2023-11-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_hoauser_fk_mailing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoauser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image'),
        ),
    ]
